Repository wazuh/wazuh-ansible, pull requests merged in 2020-11, with the labels that each got.

#481 Feature manager configuration unnest
  roles/wazuh/ansible-wazuh-manager/defaults/main.yml
  roles/wazuh/ansible-wazuh-manager/tasks/main.yml
Labels: status/review-needed

#478 Improve handling of run_once at opendistro-elasticsearch role
  roles/opendistro/opendistro-elasticsearch/tasks/main.yml
  roles/opendistro/opendistro-elasticsearch/tasks/security_actions.yml
Labels: status/review-needed

#486 Allow installing fixed Filebeat-oss version
  roles/wazuh/ansible-filebeat-oss/tasks/main.yml
Labels: enhancement

#496 Feature lint roles configurations
  .ansible-lint
  roles/elastic-stack/ansible-kibana/tasks/main.yml
Labels: type/enhancement

#495 Feature lint role wazuh agent
  roles/wazuh/ansible-wazuh-agent/tasks/Windows.yml
  roles/wazuh/ansible-wazuh-agent/tasks/installation_from_sources.yml
Labels: type/enhancement

#494 Feature lint role filebeat oss
  roles/wazuh/ansible-filebeat-oss/tasks/security_actions.yml
Labels: type/enhancement

#493 Lint role wazuh-manager
  roles/wazuh/ansible-wazuh-manager/tasks/installation_from_sources.yml
Labels: type/enhancement

#491 Feature lint role opendistro-elasticsearch
  roles/opendistro/opendistro-elasticsearch/defaults/main.yml
  roles/opendistro/opendistro-elasticsearch/tasks/local_actions.yml
  roles/opendistro/opendistro-elasticsearch/tasks/security_actions.yml
Labels: type/enhancement

#485 Feature agent default vars depth reduction
  roles/wazuh/ansible-wazuh-agent/defaults/main.yml
  roles/wazuh/ansible-wazuh-agent/tasks/main.yml
Labels: status/review-needed, type/enhancement

#501 roles/elastic-stack: update jvm.options template per upstream updates
  roles/elastic-stack/ansible-elasticsearch/templates/jvm.options.j2
Labels: status/review-needed

#507 Fix install task timeout on resource-constrained systems
  roles/wazuh/ansible-wazuh-agent/defaults/main.yml
  roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml
Labels: status/review-needed

#498 Feature role wazuh manager vars
  roles/wazuh/ansible-wazuh-agent/defaults/main.yml
  roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml
  roles/wazuh/ansible-wazuh-agent/tasks/Windows.yml
  roles/wazuh/ansible-wazuh-agent/vars/api_pass.yml
  roles/wazuh/ansible-wazuh-agent/vars/authd_pass.yml
Labels: status/in-progress, type/enhancement

#513 Release 4.0.3
  CHANGELOG.md
  README.md
  molecule/distributed-wazuh-elk-xpack/group_vars/all.yml
  molecule/distributed-wazuh-elk/group_vars/all.yml
  molecule/distributed-wazuh-odfe/group_vars/all.yml
  roles/elastic-stack/ansible-kibana/defaults/main.yml
  roles/opendistro/opendistro-kibana/defaults/main.yml
  roles/wazuh/ansible-filebeat-oss/defaults/main.yml
  roles/wazuh/ansible-filebeat/defaults/main.yml
  roles/wazuh/ansible-wazuh-agent/defaults/main.yml
  roles/wazuh/ansible-wazuh-manager/defaults/main.yml
Labels: status/in-progress
