Repository wazuh/wazuh-ansible, pull requests merged in 2020-03, with the labels that each got.

#375 Add chdir argument to Wazuh Kibana Plugin installation tasks
  roles/elastic-stack/ansible-kibana/tasks/build_wazuh_plugin.yml
  roles/elastic-stack/ansible-kibana/tasks/main.yml
Labels: wazuhci/runtests

#372 Fix conditionals of custom Wazuh packages installation tasks
  roles/wazuh/ansible-wazuh-manager/tasks/Debian.yml
Labels: bug, wazuhci/runtests

#371 Avoid to install Wazuh API in worker nodes
  roles/wazuh/ansible-wazuh-manager/tasks/Debian.yml
  roles/wazuh/ansible-wazuh-manager/tasks/RedHat.yml
  roles/wazuh/ansible-wazuh-manager/tasks/installation_from_custom_packages.yml
  roles/wazuh/ansible-wazuh-manager/tasks/installation_from_sources.yml
  roles/wazuh/ansible-wazuh-manager/tasks/main.yml
Labels: wazuhci/runtests

#377 Support Centos/RHEL 8
  roles/wazuh/ansible-wazuh-agent/tasks/installation_from_custom_packages.yml
  roles/wazuh/ansible-wazuh-manager/tasks/installation_from_custom_packages.yml
Labels: wazuhci/runtests

#380 Wazuh Ansible v3.11.4_7.6.1
  CHANGELOG.md
  VERSION
  playbooks/wazuh-agent.yml
  roles/elastic-stack/ansible-elasticsearch/defaults/main.yml
  roles/elastic-stack/ansible-elasticsearch/tasks/Debian.yml
  roles/elastic-stack/ansible-elasticsearch/tasks/RMDebian.yml
  roles/elastic-stack/ansible-elasticsearch/tasks/RMRedHat.yml
  roles/elastic-stack/ansible-elasticsearch/tasks/RedHat.yml
  roles/elastic-stack/ansible-kibana/defaults/main.yml
  roles/elastic-stack/ansible-kibana/tasks/Debian.yml
  roles/elastic-stack/ansible-kibana/tasks/RMDebian.yml
  roles/elastic-stack/ansible-kibana/tasks/RMRedHat.yml
  roles/elastic-stack/ansible-kibana/tasks/RedHat.yml
  roles/elastic-stack/ansible-kibana/tasks/build_wazuh_plugin.yml
  roles/elastic-stack/ansible-kibana/tasks/main.yml
  roles/wazuh/ansible-filebeat/defaults/main.yml
  roles/wazuh/ansible-filebeat/tasks/Debian.yml
  roles/wazuh/ansible-filebeat/tasks/RMDebian.yml
  roles/wazuh/ansible-filebeat/tasks/RMRedHat.yml
  roles/wazuh/ansible-filebeat/tasks/RedHat.yml
  roles/wazuh/ansible-filebeat/tasks/main.yml
  roles/wazuh/ansible-wazuh-agent/defaults/main.yml
  roles/wazuh/ansible-wazuh-agent/tasks/Debian.yml
  roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml
  roles/wazuh/ansible-wazuh-agent/tasks/RedHat.yml
  roles/wazuh/ansible-wazuh-agent/tasks/Windows.yml
  roles/wazuh/ansible-wazuh-agent/tasks/installation_from_custom_packages.yml
  roles/wazuh/ansible-wazuh-manager/README.md
  roles/wazuh/ansible-wazuh-manager/defaults/main.yml
  roles/wazuh/ansible-wazuh-manager/tasks/Debian.yml
  roles/wazuh/ansible-wazuh-manager/tasks/RedHat.yml
  roles/wazuh/ansible-wazuh-manager/tasks/installation_from_custom_packages.yml
  roles/wazuh/ansible-wazuh-manager/tasks/installation_from_sources.yml
  roles/wazuh/ansible-wazuh-manager/tasks/main.yml
  roles/wazuh/ansible-wazuh-manager/templates/var-ossec-etc-shared-agent.conf.j2
  roles/wazuh/ansible-wazuh-manager/vars/wazuh_api_creds.yml
Labels: wazuhci/runtests

#381 Remove Windows MD5 verification
  roles/wazuh/ansible-wazuh-agent/defaults/main.yml
  roles/wazuh/ansible-wazuh-agent/tasks/Windows.yml
Labels: wazuhci/runtests

#383 Add flag to enable/disable Windows MD5 check
  roles/wazuh/ansible-wazuh-agent/defaults/main.yml
  roles/wazuh/ansible-wazuh-agent/tasks/Windows.yml
Labels: wazuhci/runtests

#386 Bump NodeJS version to 10.x
  roles/elastic-stack/ansible-kibana/defaults/main.yml
Labels: enhancement, wazuhci/runtests

#385 NodeJS node_options variable and Kibana plugin optimization
  roles/elastic-stack/ansible-kibana/defaults/main.yml
  roles/elastic-stack/ansible-kibana/tasks/build_wazuh_plugin.yml
  roles/elastic-stack/ansible-kibana/tasks/main.yml
Labels: wazuhci/runtests

#382 Restrictive permissions on filebeat sensitive files
  roles/elastic-stack/ansible-elasticsearch/tasks/xpack_security.yml
  roles/elastic-stack/ansible-kibana/tasks/build_wazuh_plugin.yml
  roles/elastic-stack/ansible-kibana/tasks/main.yml
  roles/wazuh/ansible-filebeat/tasks/config.yml
  roles/wazuh/ansible-filebeat/tasks/main.yml
  roles/wazuh/ansible-wazuh-agent/tasks/installation_from_sources.yml
  roles/wazuh/ansible-wazuh-manager/tasks/installation_from_sources.yml
  roles/wazuh/ansible-wazuh-manager/tasks/main.yml
Labels: wazuhci/runtests

#389 Adding explicit registration address variable for wazuh-agent role
  roles/wazuh/ansible-wazuh-agent/README.md
  roles/wazuh/ansible-wazuh-agent/defaults/main.yml
  roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml
  roles/wazuh/ansible-wazuh-agent/tasks/Windows.yml
Labels: enhancement, wazuhci/runtests

#391 Removed bad formed XML comments.
  roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml
  roles/wazuh/ansible-wazuh-agent/templates/var-ossec-etc-ossec-agent.conf.j2
  roles/wazuh/ansible-wazuh-manager/templates/var-ossec-etc-ossec-server.conf.j2
  roles/wazuh/ansible-wazuh-manager/templates/var-ossec-etc-shared-agent.conf.j2
Labels: wazuhci/runtests

#392 Added registration address var to default wazuh-agent playbook
  playbooks/wazuh-agent.yml
Labels: enhancement

#361 Add the option to create agent groups and add an agent to 1 or more group
  roles/wazuh/ansible-wazuh-agent/defaults/main.yml
  roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml
  roles/wazuh/ansible-wazuh-manager/defaults/main.yml
  roles/wazuh/ansible-wazuh-manager/tasks/main.yml
Labels: wazuhci/runtests

#393 Rule paths are now relative to playbooks
  playbooks/wazuh-agent.yml
  playbooks/wazuh-elastic.yml
  playbooks/wazuh-elastic_stack-distributed.yml
Labels: enhancement

#396 Wazuh release v3.12.0 7.6.1
  playbooks/wazuh-agent.yml
  playbooks/wazuh-elastic.yml
  playbooks/wazuh-elastic_stack-distributed.yml
  roles/elastic-stack/ansible-elasticsearch/tasks/xpack_security.yml
  roles/elastic-stack/ansible-elasticsearch/templates/wazuh-elastic7-template-alerts.json.j2
  roles/elastic-stack/ansible-kibana/defaults/main.yml
  roles/elastic-stack/ansible-kibana/tasks/build_wazuh_plugin.yml
  roles/elastic-stack/ansible-kibana/tasks/main.yml
  roles/wazuh/ansible-filebeat/tasks/config.yml
  roles/wazuh/ansible-filebeat/tasks/main.yml
  roles/wazuh/ansible-wazuh-agent/README.md
  roles/wazuh/ansible-wazuh-agent/defaults/main.yml
  roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml
  roles/wazuh/ansible-wazuh-agent/tasks/Windows.yml
  roles/wazuh/ansible-wazuh-agent/tasks/installation_from_sources.yml
  roles/wazuh/ansible-wazuh-agent/templates/var-ossec-etc-ossec-agent.conf.j2
  roles/wazuh/ansible-wazuh-manager/defaults/main.yml
  roles/wazuh/ansible-wazuh-manager/tasks/installation_from_sources.yml
  roles/wazuh/ansible-wazuh-manager/tasks/main.yml
  roles/wazuh/ansible-wazuh-manager/templates/var-ossec-etc-ossec-server.conf.j2
  roles/wazuh/ansible-wazuh-manager/templates/var-ossec-etc-shared-agent.conf.j2
Labels: wazuhci/runtests
